#ifndef CONFIG_H
#define CONFIG_H

#define SERVER_ADDRESS "127.0.0.1"
#define SERVER_PORT 9876
#define SERVER_MAX_MESSAGES_READ 128

#define CERTIFICATE_FILE "../crt/cert.pem"
#define PRIVATE_KEY_FILE "../crt/private_key.pem"

#define SERVER_FPS 10
#define SERVER_MILLISECONDS_PER_FRAME 1000000 / SERVER_FPS

#define CLIENT_FPS 10
#define CLIENT_MILLISECONDS_PER_FRAME 1000000 / CLIENT_FPS
#define CLIENT_RECONNECT_TIME 3
#define CLIENT_MAX_MESSAGES_READ 64

#define CLIENT_MS_PER_PING 1000
#define CLIENT_MS_PER_CLOCK_SYNC 500

#define MAP_WIDTH 800
#define MAP_HEIGHT 600

#endif // CONFIG_H
