name: build
run-name: ${{ github.head_ref || github.ref_name }}-build


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2.0.1
        with:
          cmake-version: "3.16.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcmocka-dev gcovr

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make
