name: Test and generate coverage report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: "3.16.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcmocka-dev gcovr

      - name: Generate coverage report
        run: |
          mkdir build
          cd build
          cmake ..
          make gcov

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: build/coverage
